version: "3.8"

services:
  db:
    container_name: postgres
    build: ./db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  pg-admin:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    restart: on-failure
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  db_initial_insert:
    build: ./db_initial_insert
    volumes:
     - rowdata:/db_initial_insert
    restart: on-failure
    depends_on:
      - pg-admin
      - db

  flyway:
    image: redgate/flyway
    container_name: flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway/conf/:/flyway/conf
      - ./flyway/sql/:/flyway/sql
    depends_on:
      db_initial_insert:
          condition: service_completed_successfully

  app:
    build: ./app
    volumes:
     - appdata:/appd
    restart: on-failure
    depends_on:
      flyway:
          condition: service_completed_successfully
    ports:
      - "5555:5555"

  redis:
    image: redis
    ports:
      - 6379

volumes: 
  data: null
  pgadmin: null
  appdata: null
  rowdata: null